INSERT INTO T_SIP_DEPARTAMENTO VALUES(
    01,
    'RECURSOS HUMANOS'
);

INSERT INTO t_sip_departamento VALUES(
    02,
    'FINANCEIRO'
);

INSERT INTO T_SIP_DEPARTAMENTO VALUES(
    03,
    'FISCAL'
);

INSERT INTO T_SIP_DEPARTAMENTO VALUES(
    04,
    'COMERCIAL'
);

INSERT INTO T_SIP_DEPARTAMENTO VALUES(
    05,
    'TÉCNICO'
);

INSERT INTO T_SIP_DEPARTAMENTO VALUES(
    06,
    'MARKETING'
);

SELECT * FROM T_SIP_DEPARTAMENTO;